### ISSUE TITLE
Kan kjøpe periodekort (30 dager, 180 dager)

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#63]
## Behov og beskrivelse

Sikre at det er mulig med ende-til-ende å gjennomføre kjøp av både 30 dager og 180 dager.

Se egne oppgaver for design, som ikke inngår i denne oppgaven:

- Add all details in summary pane while shopping #20
- Oppdater design for Gyldighet og Soner #41

## Tasks

- [x] #39 
- [x] #36 

## Akseptansekriterier
- [ ] Bruker kan enkelt velge enten periodebillett 30 dager eller 180 dager
- [ ] For periodebillett skal kun gyldige kategories velges (ungdom utgår f.eks)
- [ ] Bruker får betalt billetten med Vipps
- [ ] Bruker gjenfinner billett og gyldighetsperiode fra "Min profil"
- [ ] Soner er forhåndsvalgt til A - A
- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir tydelig feilmelding gitt at kjøp feiler.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Kjøp mangler nå soner ved kjøp i nettbutikk.

**Comment by mikaelbr** [comment]
Manglende soner gjelder en endring i datagrunnlag som ikke er bakoverkompatibel. Det blir løst utenfor klientene.

**Comment by mikaelbr** [comment]
@tormoseng Kan du kjøre QA på denne?

**Comment by tormoseng** [comment]
Testet OK i staging med både 30 og 180 for flere typer nettlesere.

Små observasjoner @mikaelbr 
- Vet ikke om dette gjelder kun staging, men betaling med bankkort leder tilbake til nettbutikk via en fin AtB-logo, mens betaling med Vipps gir en HTTP 404 mot GET .../thanks. Betaling og billett er imdlertid OK.
- Hver gyldige billett har "Detaljer" og "Vis", og samme etter detaljvisning med "Detaljer" og "Skjul". Mer intuitivt med kun "Vis detaljer" og "Skjul detaljer"?

**Comment by mikaelbr** [comment]
> Hver gyldige billett har "Detaljer" og "Vis", og samme etter detaljvisning med "Detaljer" og "Skjul". Mer intuitivt med kun "Vis detaljer" og "Skjul detaljer"?

Denne tenker blir en del av #70. Jeg har ikke sett på oversiktsvisningen enda.

> Vet ikke om dette gjelder kun staging, men betaling med bankkort leder tilbake til nettbutikk via en fin AtB-logo, mens betaling med Vipps gir en HTTP 404 mot GET .../thanks. Betaling og billett er imdlertid OK.

Bra! Husker nå det var noe snakk om det der. Jeg skal sette meg inn i hvordan flyten her går. 👍

**Comment by mikaelbr** [comment]
Innser at det egentlig burde være mer i det du skriver til slutt her @tormoseng . Jeg opprettet en sak med litt mer kontekst og akseptansekriterier: https://github.com/AtB-AS/webshop/issues/85
